apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbiauto
  labels:
    app: pbiauto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbiauto
  template:
    metadata:
      labels:
        app: pbiauto
    spec:
      containers:
        - name: pbiauto
          image: philips09/myimage:1.0.18
          ports:
            - containerPort: 80
          env:
            - name: MY_SERVER
              valueFrom:
                configMapKeyRef:
                  name: pbiauto-config
                  key: DB_SERVER
            - name: MY_USER
              valueFrom:
                configMapKeyRef:
                  name: pbiauto-config
                  key: DB_USER
            - name: MY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pbiauto-config
                  key: DB_PASSWORD
