apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbiauto
  labels:
    app: pbiauto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbiauto
  template:
    metadata:
      labels:
        app: pbiauto
    spec:
      containers:
        - name: pbiauto
          image: philips09/myimage:1.0.47
          ports:
            - containerPort: 80
          env:
            - name: REPORT_SERVER
              valueFrom:
                secretKeyRef:
                  name: pbiauto-secret
                  key: REPORT_SERVER
            - name: DB_AD_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: pbiauto-secret
                  key: DB_AD_ACCOUNT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pbiauto-secret
                  key: DB_PASSWORD
