apiVersion: v1
kind: Service
metadata:
  name: pbiauto-service
spec:
  type: LoadBalancer
  selector:
    app: pbiauto
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
